name: llfile
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1



environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rust_lib_llfile:
    path: rust_builder
  flutter_rust_bridge: 2.9.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  window_manager: ^0.4.3
  event_bus: ^2.0.1
  multi_split_view: ^3.6.0
  multi_column_list_view: ^0.0.10
#  multi_column_list_view:
#    path: ../flt_pkgs/flutter_multi_column_list_view
  package_info_plus: ^8.0.1
  path_provider: ^2.1.5
  path: 1.9.1
  get: ^4.6.6
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  flutter_colorful_tab_keep: ^0.1.2
#  flutter_colorful_tab_keep:
#    path: ../flt_pkgs/flutter_colorful_tab_keep
  dynamic_tabbar: ^1.0.9
  contextmenu: ^3.0.0
  archive: ^4.0.2
  flutter_fancy_tree_view: ^1.6.0
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  dio: ^5.8.0+1
  pretty_json: ^2.0.0
  pal_dio_util: ^0.0.1
#  pal_dio_util:
#    path: ../flt_pkgs/flutter_dio_util
  flutter_markdown: ^0.7.6+2
  code_text_field: ^1.1.0
  linked_scroll_controller: ^0.2.0
  highlight: ^0.7.0
  flutter_highlight: ^0.7.0
  uuid: ^4.5.1
  fluent_ui: ^4.11.2
  top_modal_sheet: ^2.1.0
  file_picker: ^10.1.4
  easy_isolate: ^1.3.1
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.11

flutter:

  uses-material-design: true

  assets:
    - assets/images/file-ext-icons.zip

  fonts:
    - family: NotoSansSC
      fonts:
        - asset: assets/fonts/NotoSansSC-Regular.ttf
          weight: 400
          style: normal

  generate: true