[package]
name = "rust_lib_llfile"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.92"
chrono = "0.4.39"
flutter_rust_bridge = "=2.5.1"
sysinfo = { version = "0.33.0" }
