// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Stream<FsEntity> getFsEntities({required String rootPath}) =>
    RustLib.instance.api.crateApiLlfsGetFsEntities(rootPath: rootPath);

class FsEntity {
  final String name;
  final bool isDir;
  final String dateCreated;

  const FsEntity({
    required this.name,
    required this.isDir,
    required this.dateCreated,
  });

  @override
  int get hashCode => name.hashCode ^ isDir.hashCode ^ dateCreated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FsEntity &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          isDir == other.isDir &&
          dateCreated == other.dateCreated;
}
