// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `load_config_from_file`, `make_blobs_rpc_client`, `make_sb_rpc_client`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`, `from`, `from`

Future<String> createSandbarNode(
        {required String configFilePath,
        required bool parentDirAutoCreate,
        required String palCbPrivateKeyB64,
        required String palCbPublicKeyB64,
        BigInt? rpcPort,
        BigInt? sbRpcPort,
        required List<String> relayNodes,
        required String sbcApiHost}) =>
    RustLib.instance.api.crateApiSandbarNodeCreateSandbarNode(
        configFilePath: configFilePath,
        parentDirAutoCreate: parentDirAutoCreate,
        palCbPrivateKeyB64: palCbPrivateKeyB64,
        palCbPublicKeyB64: palCbPublicKeyB64,
        rpcPort: rpcPort,
        sbRpcPort: sbRpcPort,
        relayNodes: relayNodes,
        sbcApiHost: sbcApiHost);

Future<BigInt> getRpcPort() =>
    RustLib.instance.api.crateApiSandbarNodeGetRpcPort();

Future<void> startSandbarNodeService({required String configFilePath}) =>
    RustLib.instance.api.crateApiSandbarNodeStartSandbarNodeService(
        configFilePath: configFilePath);

Future<void> stopSandbarNodeService({required String configFilePath}) => RustLib
    .instance.api
    .crateApiSandbarNodeStopSandbarNodeService(configFilePath: configFilePath);

Future<SandbarNodeStat> getSandbarNodeStat({required String configFilePath}) =>
    RustLib.instance.api
        .crateApiSandbarNodeGetSandbarNodeStat(configFilePath: configFilePath);

Stream<SandbarFsAddPathResponse> addPathToSandbarFs(
        {required String configFilePath,
        required String path,
        String? wrapName}) =>
    RustLib.instance.api.crateApiSandbarNodeAddPathToSandbarFs(
        configFilePath: configFilePath, path: path, wrapName: wrapName);

class SandbarFsAddPathResponse {
  final String jsonData;
  final String kind;

  const SandbarFsAddPathResponse({
    required this.jsonData,
    required this.kind,
  });

  @override
  int get hashCode => jsonData.hashCode ^ kind.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandbarFsAddPathResponse &&
          runtimeType == other.runtimeType &&
          jsonData == other.jsonData &&
          kind == other.kind;
}

class SandbarNodeStat {
  final BigInt rpcPort;
  final BigInt sbRpcPort;
  final bool running;

  const SandbarNodeStat({
    required this.rpcPort,
    required this.sbRpcPort,
    required this.running,
  });

  @override
  int get hashCode => rpcPort.hashCode ^ sbRpcPort.hashCode ^ running.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SandbarNodeStat &&
          runtimeType == other.runtimeType &&
          rpcPort == other.rpcPort &&
          sbRpcPort == other.sbRpcPort &&
          running == other.running;
}
